#!/usr/bin/env bash
# Step 04 — Prompt for credentials, write .env, copy to Pi
# SECURITY: credentials are prompted interactively and NEVER written to git.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

ENV_FILE="${REPO_ROOT}/.env"

log_section "Step 04 — Configure Credentials"

echo ""
echo "This step collects credentials needed for DUMB."
echo "Values are written to ${ENV_FILE} (gitignored) and copied to the Pi."
echo "They are NEVER stored in git."
echo ""

# ── Helper: prompt for a secret value (no echo) ───────────────────────────────
prompt_secret() {
  local var_name="$1"
  local prompt_msg="$2"
  local value=""
  while [[ -z "${value}" ]]; do
    read -r -s -p "${prompt_msg}: " value
    echo ""
    if [[ -z "${value}" ]]; then
      echo "  Value cannot be empty. Try again."
    fi
  done
  printf -v "${var_name}" '%s' "${value}"
}

# ── Helper: prompt for a plain value with a default ──────────────────────────
prompt_plain() {
  local var_name="$1"
  local prompt_msg="$2"
  local default="$3"
  local value=""
  read -r -p "${prompt_msg} [${default}]: " value
  value="${value:-${default}}"
  printf -v "${var_name}" '%s' "${value}"
}

# ── Real-Debrid API Token ─────────────────────────────────────────────────────
echo "1. Real-Debrid API Token"
echo "   Get from: https://real-debrid.com/apitoken"
prompt_secret RD_API_TOKEN "   Enter RD_API_TOKEN"

# ── Plex Claim Token ──────────────────────────────────────────────────────────
echo ""
echo "2. Plex Claim Token (EXPIRES IN 4 MINUTES)"
echo "   Open this URL now and paste the token below:"
echo "   https://plex.tv/claim"
prompt_secret PLEX_CLAIM "   Enter PLEX_CLAIM"

# ── Plex Auth Token ───────────────────────────────────────────────────────────
echo ""
echo "3. Plex Authentication Token (permanent, different from claim token)"
echo "   How to find it:"
echo "   - Sign in to https://plex.tv"
echo "   - Open: https://plex.tv/auth/resources?includeRelays=1"
echo "   - Look for 'authToken' in the JSON response"
echo "   - Or: in Plex Web → Account → Plex Token (in URL params)"
prompt_secret PLEX_TOKEN "   Enter PLEX_TOKEN"

# ── Timezone ──────────────────────────────────────────────────────────────────
echo ""
echo "4. Timezone"
echo "   Reference: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
prompt_plain TZ "   Enter timezone" "America/New_York"

# ── PUID / PGID ───────────────────────────────────────────────────────────────
echo ""
echo "5. User/Group IDs for file permissions"
echo "   Run 'id' on your Pi to check. Usually 1000/1000 for user 'pi'."
prompt_plain PUID "   Enter PUID" "1000"
prompt_plain PGID "   Enter PGID" "1000"

# ── Write .env ────────────────────────────────────────────────────────────────
echo ""
log_step "Writing ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Generated by 04-configure-env.sh — DO NOT COMMIT
# This file is gitignored.

RD_API_TOKEN=${RD_API_TOKEN}
PLEX_CLAIM=${PLEX_CLAIM}
PLEX_TOKEN=${PLEX_TOKEN}
TZ=${TZ}
PUID=${PUID}
PGID=${PGID}
EOF

# Protect file permissions (owner read only)
chmod 600 "${ENV_FILE}"
log_ok ".env written with restricted permissions (600)"

# ── Verify gitignore ──────────────────────────────────────────────────────────
if git -C "${REPO_ROOT}" check-ignore -q "${ENV_FILE}" 2>/dev/null; then
  log_ok ".env is properly gitignored"
else
  log_warn ".env may NOT be gitignored! Check .gitignore before committing."
fi

# ── Copy to Pi ────────────────────────────────────────────────────────────────
check_ssh_connectivity

log_step "Copying .env to Pi at /opt/dumb/.env ..."
pi_scp "${ENV_FILE}" "/opt/dumb/.env"
pi_ssh "chmod 600 /opt/dumb/.env"
log_ok ".env copied to Pi with restricted permissions (600)"

echo ""
log_ok "Step 04 complete — credentials configured."
